# SPDX-FileCopyrightText: 2022 Mathijs de Bruin <mathijs@mathijsfietst.nl>
# SPDX-FileCopyrightText: 2022 Dweb-search-frontend
#
# SPDX-License-Identifier: AGPL-3.0-only


plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      extensions:
        - .es6
        - .js
        - .jsx
        - .mjs
        - .vue
