# SPDX-FileCopyrightText: 2022 Mathijs de Bruin <mathijs@mathijsfietst.nl>
# SPDX-FileCopyrightText: 2022 Dweb-search-frontend
#
# SPDX-License-Identifier: AGPL-3.0-only


include:
  - template: Auto-DevOps.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Auto-DevOps.gitlab-ci.yml

variables:
  TEST_DISABLED: "true"
  DAST_DISABLED: "true"
  AUTO_DEVOPS_BUILD_CACHE: "registry"
  AUTO_BUILD_IMAGE_VERSION: "v1.6.0"
  AUTO_DEVOPS_BUILD_CACHE_REF: "$CI_REGISTRY_IMAGE/cache:latest"

reuse:
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint
